pydio:
  build: .
  links:
    - mysql
  ports:
    - "443:443"
  volumes:
    - var-www-pydio-data:/var/www/pydio/data
  restart: always
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD:
    MYSQL_DATABASE: pydio
    MYSQL_USER: pydio
    MYSQL_PASSWORD:
  volumes:
    - var-lib-mysql:/var/lib/mysql
  restart: always
